/**
 * Bundles the app code the Life functions run — moments-entry.ts into
 * functions/generated/moments.js and events-entry.ts into generated/events.js
 * (CommonJS, for the Life functions, which have no build step).
 *
 * Uses Rolldown, which Vite already installs — no new dependency. Pass
 * --check to build into memory and fail if the committed file differs.
 */
import { rolldown } from 'rolldown'
import { readFile, writeFile, mkdir } from 'node:fs/promises'

const ENTRIES = [
  { input: 'src/server/moments-entry.ts', out: 'functions/generated/moments.js' },
  { input: 'src/server/events-entry.ts', out: 'functions/generated/events.js' },
]
const banner = (input) => `// GENERATED by scripts/build-moments.mjs from ${input}.
// Do not edit — run \`npm run build:moments\`. verify-moments-bundle checks it is current.
`
let stale = 0
for (const { input, out } of ENTRIES) {
  const bundle = await rolldown({ input, platform: 'node', logLevel: 'warn' })
  const { output } = await bundle.generate({ format: 'cjs', banner: banner(input) })
  await bundle.close()
  const code = output[0].code
  if (process.argv.includes('--check')) {
    const current = await readFile(out, 'utf8').catch(() => '')
    if (current !== code) {
      stale++
      console.log(`  ✗ ${out} is stale — run \`npm run build:moments\` and commit it`)
    } else console.log(`  ✓ ${out} matches the code it was built from`)
  } else {
    await mkdir('functions/generated', { recursive: true })
    await writeFile(out, code)
    console.log(`wrote ${out} (${(code.length / 1024).toFixed(0)} kB)`)
  }
}
if (process.argv.includes('--check')) {
  console.log(stale ? `\n${stale} failed\n` : '\nfunctions bundles verified\n')
  process.exit(stale ? 1 : 0)
}
