/**
 * Bundles src/server/moments-entry.ts into functions/generated/moments.js
 * (CommonJS, for the Life functions, which have no build step).
 *
 * Uses Rolldown, which Vite already installs — no new dependency. Pass
 * --check to build into memory and fail if the committed file differs.
 */
import { rolldown } from 'rolldown'
import { readFile, writeFile, mkdir } from 'node:fs/promises'

const OUT = 'functions/generated/moments.js'
const BANNER = `// GENERATED by scripts/build-moments.mjs from src/server/moments-entry.ts.
// Do not edit — run \`npm run build:moments\`. verify-moments-bundle checks it is current.
`
const bundle = await rolldown({ input: 'src/server/moments-entry.ts', platform: 'node', logLevel: 'warn' })
const { output } = await bundle.generate({ format: 'cjs', banner: BANNER })
await bundle.close()
const code = output[0].code

if (process.argv.includes('--check')) {
  const current = await readFile(OUT, 'utf8').catch(() => '')
  if (current !== code) {
    console.log(`  ✗ ${OUT} is stale — run \`npm run build:moments\` and commit it`)
    process.exit(1)
  }
  console.log(`  ✓ ${OUT} matches the engines it was built from\n\nmoments bundle verified\n`)
} else {
  await mkdir('functions/generated', { recursive: true })
  await writeFile(OUT, code)
  console.log(`wrote ${OUT} (${(code.length / 1024).toFixed(0)} kB)`)
}
